### ISSUE TITLE
data converter改进

### ISSUE THREAD

**Issue by JeasonCao** [Castersorium/0vbbElectronics#10]
### bugs
- 当出现十杀一的内容时，会报错，因为十杀一的文件没有开始时间
  - \\nas.orisco.work\LAB101_ARCHIVE\RUNs\RUN2404\PID240429\shishayi
- 重命名过的文件，会报group数大于2的错，虽然在excel中查看group数还是为1
  - \\nas.orisco.work\LAB101_ARCHIVE\RUNs\RUN2404\PID240429\groupbiggerthan2
### 改进
- 可以加一个log作为输出

**Comment by Destiny712** [comment]
收到！

**Comment by Destiny712** [comment]
Done!
