### ISSUE TITLE
Plot the graph from the root file

### ISSUE THREAD

**Issue by cupid-fudan** [Castersorium/0vbbElectronics#4]
- Use the data from `Resistence_measurement.root`
- Use Root to plot the histogram and save it
- Fix the `segment error` if possible

**Comment by Destiny712** [comment]
Fixed the segment error if possible.
See this [commit](https://github.com/Castersorium/0vbbElectronics/commit/18d8532a09dce8b52d2537cf38aca3c80689bea5#).

**Comment by Castersorium** [comment]
`ROOTDataPlotter.hpp` and other `include/**` has characters encoding issue, eg:
```c
// ���ڱ�������ļ�
// ���ڻ���ͼ��
```

**Comment by Destiny712** [comment]
收到

**Comment by cupid-fudan** [comment]
This issue has been fixed in this [commit](https://github.com/Castersorium/0vbbElectronics/commit/7aa49c905b9120375a9ff56368b5d7a14d1ef617)
